# Generated by Django 4.0.4 on 2022-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
                ('capacity', models.PositiveIntegerField()),
                ('plate_no', models.CharField(max_length=100)),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=100)),
                ('Transmission', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
