# Generated by Django 4.0.4 on 2022-05-22 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='Arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
