# Generated by Django 4.0.4 on 2022-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_route_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
