# Generated by Django 4.0.4 on 2022-06-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experienced', models.PositiveIntegerField(default=0)),
                ('total_cars', models.PositiveIntegerField(default=0)),
                ('happy_customers', models.PositiveIntegerField(default=0)),
                ('total_branches', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Section_Counter',
            },
        ),
    ]
