# Generated by Django 4.0.4 on 2022-06-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_section_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_counter',
            name='total_cars',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
