# Generated by Django 4.0.4 on 2022-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
