# Generated by Django 4.0.4 on 2022-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
